In [29]:
import pandas as pd
TRAIN_DATASET ="C:\\Users\\Owner\\Downloads\\housing\\train.csv"
TEST_DATASET ="C:\\Users\\Owner\\Downloads\\housing\\test.csv"
training_data = pd.read_csv(TRAIN_DATASET)
test_data = pd.read_csv(TEST_DATASET)
training_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
cat_attribs=["MSZoning",
"Street",
"Alley",
"LotShape",
"LandContour",
"Utilities",
"LotConfig",
"LandSlope",
"Neighborhood",
"Condition1",
"Condition2",
"BldgType",
"HouseStyle",
"RoofStyle",
"RoofMatl",
"Exterior1st",
"Exterior2nd",
"MasVnrType",
"ExterQual",
"ExterCond",
"Foundation",
"BsmtQual",
"BsmtCond",
"BsmtExposure",
"BsmtFinType1",
"BsmtFinType2",
"Heating",
"HeatingQC",
"CentralAir",
"Electrical",
"KitchenQual",
"Functional",
"FireplaceQu",
"GarageType",
"GarageFinish",
"GarageQual",
"GarageCond",
"PavedDrive",
"PoolQC",
"Fence",
"MiscFeature",
"SaleType",
"SaleCondition"]
num_attribs = training_data.columns.drop(cat_attribs).drop(["SalePrice"])
train_labels = training_data["SalePrice"]
dropped_train_salesprice= training_data.drop(columns=["SalePrice"])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ("ord", OrdinalEncoder()),
])

columntrans=ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="most_frequent"), num_attribs),
        ("cat", cat_pipeline, cat_attribs)
    ]

)
preprocessor = columntrans.fit_transform(dropped_train_salesprice)

In [30]:
df = pd.DataFrame(preprocessor)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.0,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
1,2.0,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
2,3.0,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
3,4.0,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,...,5.0,2.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,0.0
4,5.0,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0

In [21]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(preprocessor, train_labels)
pd.DataFrame(some_data_prepared).head()

,0,1,2,3,4,5,6,7,8,9,...,67,68,69,70,71,72,73,74,75,76
0,1.0,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2.0,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3.0,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4.0,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,5.0,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [28]:
cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ("ord", OrdinalEncoder()),
])

columntr=ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="most_frequent"), num_attribs),
        ("cat", cat_pipe, cat_attribs)
    ]

)
test_data_final = columntr.fit_transform(test_data)
for prd in lin_reg.predict(test_data_final):
    print(f"Prediction: {prd}")

Prediction: 340146.35307081207
Prediction: 394987.233252018
Prediction: 398673.49961007084
Prediction: 422007.09899070696
Prediction: 419592.58576027746
Prediction: 402201.4421119946
Prediction: 418139.79173477786
Prediction: 396597.44301830395
Prediction: 428875.5967087529
Prediction: 341465.71051251236
Prediction: 432644.45574340364
Prediction: 338739.60668703914
Prediction: 324920.44659189484
Prediction: 376038.32971174177
Prediction: 338981.8562982273
Prediction: 582055.299665666
Prediction: 470939.0195819647
Prediction: 537407.8718386816
Prediction: 531475.8707197797
Prediction: 660257.776646919
Prediction: 518561.32505842624
Prediction: 444214.8046108284
Prediction: 411019.0383245691
Prediction: 405717.3806134849
Prediction: 432877.659503937
Prediction: 442935.4888587273
Prediction: 528582.5168201723
Prediction: 474050.37997385464
Prediction: 421485.2711923027
Prediction: 479190.179430926
Prediction: 453447.8690052915
Prediction: 323046.47429605294
Prediction: 433481.19984058524
Prediction: 519721.4230923066
Prediction: 498833.8171032828
Prediction: 482499.9147582848
Prediction: 401808.3639659921
Prediction: 407366.8482830529
Prediction: 396397.44823948434
Prediction: 396493.5105371354
Prediction: 435376.944820154
Prediction: 382620.3631533326
Prediction: 513251.89328210335
Prediction: 474622.5554031909
Prediction: 458285.1637338733
Prediction: 430839.3553827419
Prediction: 476625.8055783871
Prediction: 432063.50778542366
Prediction: 382885.0772299934
Prediction: 369607.19558071205
Prediction: 383328.2835895312
Prediction: 412133.7172824936
Prediction: 386746.173972863
Prediction: 371071.19063535007
Prediction: 451089.42182290903
Prediction: 395988.94536570855
Prediction: 401168.81170214014
Prediction: 350992.35177684855
Prediction: 465668.9128945337
Prediction: 362675.7415258931
Prediction: 355954.184031341
Prediction: 423457.0425159449
Prediction: 329991.68422158295
Prediction: 356573.30970994267
Prediction: 324048.6260894458
Prediction: 319432.1385628027
Prediction: 322665.36199258873
Prediction: 379451.7773961802
Prediction: 369878.2887322132
Prediction: 434120.2832650379
Prediction: 380495.858080324
Prediction: 342501.39402343635
Prediction: 398471.15954652685
Prediction: 385090.40855876426
Prediction: 392625.6208956593
Prediction: 340851.4082451102
Prediction: 272465.08639514353
Prediction: 395100.4584605179
Prediction: 469977.03281746665
Prediction: 343282.23570261593
Prediction: 377747.7379504633
Prediction: 375556.0386985999
Prediction: 421330.1776550389
Prediction: 323536.4584718575
Prediction: 337091.7588856553
Prediction: 370549.36546991835
Prediction: 384105.83663742244
Prediction: 363570.4777537186
Prediction: 341959.33012535586
Prediction: 364709.5334674646
Prediction: 368653.64903684426
Prediction: 368662.73906981177
Prediction: 394275.71449955716
Prediction: 348295.23728831415
Prediction: 401582.3155236093
Prediction: 308991.2802887636
Prediction: 346036.21733628144
Prediction: 349619.3957661148
Prediction: 305538.6772429638
Prediction: 372192.36214299523
Prediction: 376262.3586282532
Prediction: 368548.94735736493
Prediction: 348602.4210420686
Prediction: 394248.3325053039
Prediction: 364505.3728609113
Prediction: 468439.4330097907
Prediction: 312999.79713831237
Prediction: 468525.90238505276
Prediction: 355887.83455110923
Prediction: 371977.0467552601
Prediction: 328486.3727096438
Prediction: 371197.0475821411
Prediction: 484969.95548035274
Prediction: 344182.6245807053
Prediction: 471083.69747119653
Prediction: 482690.0805234406
Prediction: 423654.8276390196
Prediction: 388616.33197847777
Prediction: 357357.73790127295
Prediction: 422968.14477933734
Prediction: 395491.42246674816
Prediction: 357211.4234756138
Prediction: 520762.20059735887
Prediction: 455597.4832165714
Prediction: 387617.4773941515
Prediction: 279287.57783052744
Prediction: 335228.83071047254
Prediction: 384702.8864365842
Prediction: 332806.7034318941
Prediction: 369184.51868391177
Prediction: 302073.6701383351
Prediction: 379858.82071150746
Prediction: 362677.9076286915
Prediction: 364568.2078776376
Prediction: 344622.93711712747
Prediction: 451214.5173042505
Prediction: 398211.14284046786
Prediction: 426467.39254000667
Prediction: 416065.2797344974
Prediction: 412399.223216587
Prediction: 268621.47867652215
Prediction: 348990.8863345778
Prediction: 289051.44001165614
Prediction: 497560.9933494155
Prediction: 475853.42658112105
Prediction: 399135.21580438805
Prediction: 396194.1580416658
Prediction: 453991.0011794334
Prediction: 427681.1502904254
Prediction: 384492.46294138674
Prediction: 362220.90195576823
Prediction: 422375.5622643393
Prediction: 396870.25108298124
Prediction: 365280.33842227655
Prediction: 309122.9338175396
Prediction: 282603.5702540544
Prediction: 300899.35100933514
Prediction: 343859.25402631075
Prediction: 387252.18358817813
Prediction: 382202.3298007131
Prediction: 366031.26647727075
Prediction: 384872.55633766646
Prediction: 486856.64816192444
Prediction: 452012.9337701036
Prediction: 351460.7209518035
Prediction: 414072.71787279495
Prediction: 412369.80003237305
Prediction: 514874.99927804945
Prediction: 408727.81241155416
Prediction: 557954.2211560567
Prediction: 442251.2126243643
Prediction: 454307.3989650849
Prediction: 414281.6342609506
Prediction: 420179.5027925391
Prediction: 417204.0795334822
Prediction: 393066.19437369215
Prediction: 425977.2238900189
Prediction: 434467.6807002146
Prediction: 412710.52443077276
Prediction: 498059.01145766303
Prediction: 413973.7691303508
Prediction: 491526.71215909394
Prediction: 453695.1905579814
Prediction: 465402.4026672563
Prediction: 477804.25743110385
Prediction: 396821.93897848134
Prediction: 386202.26506425603
Prediction: 363872.90355883096
Prediction: 378091.30949790473
Prediction: 332355.9384849705
Prediction: 340641.1314358597
Prediction: 337907.9968608611
Prediction: 338694.4873992442
Prediction: 373979.16533201747
Prediction: 373937.62431253307
Prediction: 368163.22305776435
Prediction: 373170.65946124005
Prediction: 378305.13715702016
Prediction: 337923.5982861526
Prediction: 378265.4992038228
Prediction: 642654.4074637314
Prediction: 571860.5566280668
Prediction: 599987.5088285771
Prediction: 662474.4384069499
Prediction: 551095.9275766734
Prediction: 534034.5889459681
Prediction: 579372.0347305683
Prediction: 581114.5132532339
Prediction: 543774.1745996187
Prediction: 572716.2242315798
Prediction: 494631.5202876886
Prediction: 616000.3336509682
Prediction: 512645.26250441954
Prediction: 480539.49038901227
Prediction: 439740.3294871845
Prediction: 443340.16166869574
Prediction: 440870.723773984
Prediction: 648525.9212278137
Prediction: 579419.2631740817
Prediction: 554878.6841891373
Prediction: 514246.489339801
Prediction: 525335.0571031566
Prediction: 419472.19676145934
Prediction: 425085.8833367545
Prediction: 431732.6175459742
Prediction: 411724.58932722383
Prediction: 420163.04606940714
Prediction: 443330.7652966792
Prediction: 444541.45598927117
Prediction: 447521.22469439264
Prediction: 432821.4165065624
Prediction: 505674.33040963276
Prediction: 418197.88029156206
Prediction: 413893.73841717816
Prediction: 395573.1819447137
Prediction: 498759.4386750846
Prediction: 394149.5512465271
Prediction: 539785.5719619319
Prediction: 553794.0967320031
Prediction: 473391.3946866079
Prediction: 502193.9804839222
Prediction: 479764.27589247306
Prediction: 478639.7048066985
Prediction: 511241.90818551765
Prediction: 502427.63144942117
Prediction: 615601.0556180809
Prediction: 453776.9449072066
Prediction: 441441.3104107487
Prediction: 496144.9759950482
Prediction: 462645.93409784534
Prediction: 512014.54148166487
Prediction: 492813.76165329735
Prediction: 506312.4966161046
Prediction: 457805.8178632781
Prediction: 445671.06452272274
Prediction: 418005.50769047835
Prediction: 419758.0643151291
Prediction: 367698.14800360636
Prediction: 452294.2878147627
Prediction: 492224.3720122571
Prediction: 412879.62595879985
Prediction: 358601.63043994433
Prediction: 396110.7656003395
Prediction: 452242.49517374695
Prediction: 476857.36543871346
Prediction: 429917.21665677335
Prediction: 387957.47774299234
Prediction: 430478.995361977
Prediction: 400033.2503570665
Prediction: 391749.90969325416
Prediction: 361426.98319496354
Prediction: 356551.0587186895
Prediction: 337121.0058277291
Prediction: 346754.19970184774
Prediction: 378210.1500416619
Prediction: 338878.5786868036
Prediction: 529003.7904280827
Prediction: 466148.71770202415
Prediction: 492449.3982512315
Prediction: 439227.3830333974
Prediction: 422923.01086074533
Prediction: 418298.87075981195
Prediction: 424653.9238572479
Prediction: 559598.5892511627
Prediction: 449549.50309147686
Prediction: 440623.5146642749
Prediction: 448326.6632241893
Prediction: 458067.22005251027
Prediction: 396403.55247347103
Prediction: 370431.4604917639
Prediction: 492423.6365173897
Prediction: 336811.76939594536
Prediction: 384270.5043058179
Prediction: 430149.05588702485
Prediction: 416758.35724529927
Prediction: 365865.06433844566
Prediction: 341136.7915078711
Prediction: 384213.4324466868
Prediction: 395412.55293625896
Prediction: 395360.1877836585
Prediction: 381672.59011751786
Prediction: 400783.62352889497
Prediction: 416606.972810881
Prediction: 332271.3738582458
Prediction: 413842.4373615831
Prediction: 418811.1635262361
Prediction: 463970.2617542895
Prediction: 380797.1396578036
Prediction: 405536.0957634116
Prediction: 401701.2705320816
Prediction: 331941.75653511845
Prediction: 370132.39500084147
Prediction: 347331.45250970055
Prediction: 374182.66686418024
Prediction: 378155.2943845405
Prediction: 362260.46545117744
Prediction: 344232.8703181746
Prediction: 383947.9945535376
Prediction: 356594.4314790352
Prediction: 409486.9747769446
Prediction: 350611.46284436085
Prediction: 300874.14460716886
Prediction: 367146.7453025293
Prediction: 347414.6928326383
Prediction: 370623.87605970143
Prediction: 344229.9583230475
Prediction: 415156.72105613304
Prediction: 314387.0111118618
Prediction: 339540.2555690601
Prediction: 283081.01232581097
Prediction: 433309.00248257513
Prediction: 391933.5369647688
Prediction: 370094.07633508206
Prediction: 410392.26287570805
Prediction: 364132.2770475233
Prediction: 377546.1133191297
Prediction: 369482.32230532705
Prediction: 342505.6776581248
Prediction: 327577.4767262626
Prediction: 360691.1575246621
Prediction: 348258.08919762983
Prediction: 361793.09289133176
Prediction: 393355.3264685734
Prediction: 378407.58749322034
Prediction: 375202.7599138364
Prediction: 369104.2571486479
Prediction: 395167.59319715947
Prediction: 361303.8979457095
Prediction: 354124.6869746449
Prediction: 379793.24352812674
Prediction: 367461.96879710443
Prediction: 351320.15567340143
Prediction: 354299.22916174657
Prediction: 331116.3967479917
Prediction: 263331.7936585939
Prediction: 355953.3455627323
Prediction: 365316.0013019929
Prediction: 425174.15407041274
Prediction: 374795.0100621334
Prediction: 293411.0521807312
Prediction: 358471.38740169234
Prediction: 391778.348673075
Prediction: 280614.0273006547
Prediction: 375512.07901500654
Prediction: 367162.3858693931
Prediction: 332937.6623037341
Prediction: 309497.5613261196
Prediction: 366596.2240776003
Prediction: 371134.8016523486
Prediction: 384832.3326651873
Prediction: 384675.0312199781
Prediction: 308559.60152952396
Prediction: 377258.9636794112
Prediction: 360188.2882905642
Prediction: 350229.7727843183
Prediction: 355746.99386251066
Prediction: 318184.96858599153
Prediction: 338257.98397093266
Prediction: 359326.37729764986
Prediction: 365810.19769413373
Prediction: 349740.9588500925
Prediction: 320416.2370038021
Prediction: 347180.67628479097
Prediction: 374036.6013471591
Prediction: 355363.66862889635
Prediction: 385642.3688273353
Prediction: 395478.640887853
Prediction: 264441.5455296871
Prediction: 351727.07131487713
Prediction: 343743.61938036396
Prediction: 386452.45223575365
Prediction: 359811.8371920176
Prediction: 367053.10686115315
Prediction: 412773.0557888774
Prediction: 401117.323388485
Prediction: 457238.6882136557
Prediction: 370227.65247329534
Prediction: 368091.95177026256
Prediction: 338101.83859136305
Prediction: 390217.6311381981
Prediction: 338545.83406871324
Prediction: 520492.3124585808
Prediction: 519755.3123296432
Prediction: 519769.2822654403
Prediction: 579537.2230247443
Prediction: 579765.8589096502
Prediction: 464113.99010993144
Prediction: 538848.5217673595
Prediction: 454941.2711982508
Prediction: 466480.5799967565
Prediction: 490731.8576062571
Prediction: 424687.7302807076
Prediction: 463895.86348644877
Prediction: 366329.093265329
Prediction: 417975.1176727866
Prediction: 422627.93451517005
Prediction: 449259.9495222403
Prediction: 440474.5814512861
Prediction: 358398.5898953099
Prediction: 361396.1258061279
Prediction: 472061.4217530617
Prediction: 491322.244001515
Prediction: 422972.46721283253
Prediction: 437636.9888896623
Prediction: 473419.70637918473
Prediction: 522198.05390202766
Prediction: 465456.49449777673
Prediction: 505600.00919839996
Prediction: 406135.6233928364
Prediction: 328534.75337522477
Prediction: 365830.19889678294
Prediction: 317738.17636890826
Prediction: 364243.62711010897
Prediction: 342216.8481920315
Prediction: 367089.2801401494
Prediction: 362275.1065864947
Prediction: 336255.9107985459
Prediction: 352580.289530301
Prediction: 386983.2289287376
Prediction: 373588.7531658558
Prediction: 380176.15993805206
Prediction: 357496.80866694544
Prediction: 432705.8929694679
Prediction: 359540.102714665
Prediction: 419574.60632238886
Prediction: 375717.4390591406
Prediction: 439623.5923755488
Prediction: 337071.7074144678
Prediction: 373449.65600767685
Prediction: 353707.3494638314
Prediction: 422574.10226518824
Prediction: 513890.1092145811
Prediction: 395722.3246723644
Prediction: 296859.5386775101
Prediction: 536006.1619688594
Prediction: 246745.24767401442
Prediction: 479636.55479052896
Prediction: 371811.2232320735
Prediction: 417111.8562641195
Prediction: 389385.544735034
Prediction: 602064.0508906418
Prediction: 564409.6075366759
Prediction: 459857.6483863909
Prediction: 447953.4072237427
Prediction: 448460.5167422532
Prediction: 602467.267860124
Prediction: 370144.9898709471
Prediction: 397280.6640891102
Prediction: 357302.7104889562
Prediction: 363330.7539255328
Prediction: 382008.5367805436
Prediction: 375940.06521163066
Prediction: 405330.5902646852
Prediction: 399657.7285409344
Prediction: 402846.1266391636
Prediction: 418652.79151422414
Prediction: 408963.3267129075
Prediction: 421139.4960414076
Prediction: 473631.0147442019
Prediction: 418738.1980787923
Prediction: 397965.1050826127
Prediction: 428385.8800724773
Prediction: 431237.65476394887
Prediction: 550764.758366274
Prediction: 594268.8555759416
Prediction: 369190.0429334133
Prediction: 518730.8507106262
Prediction: 399152.7041871657
Prediction: 503640.42580676894
Prediction: 437583.13946336834
Prediction: 510962.67109989445
Prediction: 460489.622087511
Prediction: 431062.55166611425
Prediction: 425525.9761219674
Prediction: 355901.0812115101
Prediction: 550722.6339738637
Prediction: 388686.7716838545
Prediction: 524750.4444120424
Prediction: 369166.31828763103
Prediction: 343295.6395718006
Prediction: 354433.7841830214
Prediction: 328619.7600485564
Prediction: 344822.0002512282
Prediction: 333023.3371563575
Prediction: 370936.6400030311
Prediction: 370175.29724189546
Prediction: 514555.5226660562
Prediction: 608609.313024279
Prediction: 597693.3469660814
Prediction: 584306.2340859883
Prediction: 655373.9923083971
Prediction: 585752.3111933463
Prediction: 529639.8380857864
Prediction: 553892.7119694871
Prediction: 646968.8985459935
Prediction: 503190.9448265587
Prediction: 571836.8492525225
Prediction: 546923.4397873566
Prediction: 545754.4809805276
Prediction: 413875.89520624466
Prediction: 567841.0141689936
Prediction: 448765.81089277915
Prediction: 436218.1529196068
Prediction: 418733.7545413566
Prediction: 453202.21280621155
Prediction: 446652.6205434934
Prediction: 432692.52866150765
Prediction: 422138.1478820734
Prediction: 442921.407492934
Prediction: 464316.7205235774
Prediction: 452855.61117578996
Prediction: 474673.07727247244
Prediction: 418575.83922491944
Prediction: 467912.0283592371
Prediction: 411580.0931759109
Prediction: 511749.39179235254
Prediction: 542897.6251096029
Prediction: 517752.07986280555
Prediction: 508919.3020457777
Prediction: 536339.2218582637
Prediction: 528170.2499803198
Prediction: 494136.3571263426
Prediction: 495323.31127420976
Prediction: 520577.9668385703
Prediction: 474552.2481602982
Prediction: 450034.14275229746
Prediction: 495499.41442750115
Prediction: 459554.3699711156
Prediction: 439631.17432613205
Prediction: 454623.4346505385
Prediction: 381961.6006200153
Prediction: 418799.8619445502
Prediction: 421741.8004316564
Prediction: 437469.9041567191
Prediction: 449004.931231481
Prediction: 433282.39952542307
Prediction: 439472.2661021608
Prediction: 339651.4467814604
Prediction: 365747.7372369643
Prediction: 320348.9698337116
Prediction: 323698.1720344282
Prediction: 416323.08182808175
Prediction: 382079.74274917226
Prediction: 525007.2027570792
Prediction: 566924.9803824341
Prediction: 410076.90191653674
Prediction: 392108.05743744783
Prediction: 386454.9278075169
Prediction: 402500.2717735537
Prediction: 505691.176013286
Prediction: 484101.16424010857
Prediction: 497169.4672570594
Prediction: 498732.9382243585
Prediction: 415152.252974794
Prediction: 446505.22400443605
Prediction: 455602.677584158
Prediction: 461235.79055981175
Prediction: 551728.9085956749
Prediction: 454580.2249321793
Prediction: 561670.2501148547
Prediction: 534162.1194786907
Prediction: 440627.40413251123
Prediction: 408001.7240878232
Prediction: 404767.53049701685
Prediction: 438363.1597105949
Prediction: 361700.66033285065
Prediction: 369761.7320835956
Prediction: 381022.1853940773
Prediction: 362766.9964083631
Prediction: 411493.7280109518
Prediction: 344829.14221124584
Prediction: 344902.8886864353
Prediction: 379892.8102253191
Prediction: 317762.1167611133
Prediction: 409787.2850303855
Prediction: 386338.4861919158
Prediction: 342922.8297308015
Prediction: 452164.6646495315
Prediction: 364566.82763995463
Prediction: 412846.33049537893
Prediction: 414940.9984045627
Prediction: 345568.713921295
Prediction: 351651.06498601893
Prediction: 356330.1135593974
Prediction: 358861.9732715518
Prediction: 403808.01370691834
Prediction: 339089.5333315637
Prediction: 364850.4133460426
Prediction: 313916.8460204145
Prediction: 343192.8916629092
Prediction: 320413.4188951801
Prediction: 379447.54363315436
Prediction: 366692.6665983144
Prediction: 412724.4551857887
Prediction: 378958.35955814295
Prediction: 355980.8062544612
Prediction: 381571.8625373519
Prediction: 341682.70357060176
Prediction: 376672.1860681416
Prediction: 351655.84294379875
Prediction: 357506.1262205965
Prediction: 343680.79737101775
Prediction: 377807.466587743
Prediction: 327054.90121582407
Prediction: 340815.43573115184
Prediction: 352329.12889461895
Prediction: 363655.1659920374
Prediction: 331859.927417099
Prediction: 316387.14948567864
Prediction: 362839.49372534105
Prediction: 315339.35628024465
Prediction: 371192.22608203185
Prediction: 400817.54032477643
Prediction: 359174.64188713045
Prediction: 370457.0362658445
Prediction: 321017.46173003083
Prediction: 349728.7094932245
Prediction: 375900.27845805534
Prediction: 251830.68138233828
Prediction: 274195.0500701093
Prediction: 355054.1846605309
Prediction: 378824.82721852814
Prediction: 325357.7564574571
Prediction: 378449.5785573919
Prediction: 394333.1070725692
Prediction: 285117.43108174973
Prediction: 433938.4337878381
Prediction: 363931.98026034096
Prediction: 331405.58546763123
Prediction: 351543.2600354054
Prediction: 390420.7036704994
Prediction: 361409.38860067935
Prediction: 354636.77750046854
Prediction: 360234.8155899863
Prediction: 392344.1778754161
Prediction: 329445.2286276154
Prediction: 368277.3000376972
Prediction: 353177.4432326199
Prediction: 340490.64885511296