In [1]:
import pandas as pd
TRAIN_DATASET ="C:\\Users\\Owner\\Downloads\\housing\\train.csv"
TEST_DATASET ="C:\\Users\\Owner\\Downloads\\housing\\test.csv"
training_data = pd.read_csv(TRAIN_DATASET)
test_data = pd.read_csv(TEST_DATASET)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
cat_attribs=["MSZoning",
"Street",
"Alley",
"LotShape",
"LandContour",
"Utilities",
"LotConfig",
"LandSlope",
"Neighborhood",
"Condition1",
"Condition2",
"BldgType",
"HouseStyle",
"RoofStyle",
"RoofMatl",
"Exterior1st",
"Exterior2nd",
"MasVnrType",
"ExterQual",
"ExterCond",
"Foundation",
"BsmtQual",
"BsmtCond",
"BsmtExposure",
"BsmtFinType1",
"BsmtFinType2",
"Heating",
"HeatingQC",
"CentralAir",
"Electrical",
"KitchenQual",
"Functional",
"FireplaceQu",
"GarageType",
"GarageFinish",
"GarageQual",
"GarageCond",
"PavedDrive",
"PoolQC",
"Fence",
"MiscFeature",
"SaleType",
"SaleCondition"]
num_attribs = training_data.columns.drop(cat_attribs).drop(["SalePrice"])
train_labels = training_data["SalePrice"]
dropped_train_salesprice= training_data.drop(columns=["SalePrice"])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ("ord", OrdinalEncoder()),
])

columntrans=ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="most_frequent"), num_attribs),
        ("cat", cat_pipeline, cat_attribs)
    ]

)
preprocessor = columntrans.fit_transform(dropped_train_salesprice)

In [20]:
df = pd.DataFrame(preprocessor)
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.0,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
1,2.0,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
2,3.0,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
3,4.0,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,...,5.0,2.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,0.0
4,5.0,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
5,6.0,50.0,85.0,14115.0,5.0,5.0,1993.0,1995.0,0.0,732.0,...,1.0,2.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
6,7.0,20.0,75.0,10084.0,8.0,5.0,2004.0,2005.0,186.0,1369.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
7,8.0,60.0,60.0,10382.0,7.0,6.0,1973.0,1973.0,240.0,859.0,...,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0
8,9.0,50.0,51.0,6120.0,7.0,5.0,1931.0,1950.0,0.0,0.0,...,5.0,2.0,1.0,4.0,2.0,2.0,2.0,2.0,8.0,0.0
9,10.0,190.0,50.0,7420.0,5.0,6.0,1939.0,1950.0,0.0,851.0,...,1.0,1.0,2.0,4.0,2.0,2.0,2.0,2.0,8.0,4.0

In [21]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(preprocessor, train_labels)
pd.DataFrame(some_data_prepared).head()

,0,1,2,3,4,5,6,7,8,9,...,67,68,69,70,71,72,73,74,75,76
0,1.0,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2.0,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3.0,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4.0,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,5.0,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [27]:
cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ("ord", OrdinalEncoder()),
])

columntr=ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="most_frequent"), num_attribs),
        ("cat", cat_pipe, cat_attribs)
    ]

)
test_data_final = columntr.fit_transform(test_data)
for i in range(len(lin_reg.predict(test_data_final))):
    print(f"Id: {i}")

Id: 0
Id: 1
Id: 2
Id: 3
Id: 4
Id: 5
Id: 6
Id: 7
Id: 8
Id: 9
Id: 10
Id: 11
Id: 12
Id: 13
Id: 14
Id: 15
Id: 16
Id: 17
Id: 18
Id: 19
Id: 20
Id: 21
Id: 22
Id: 23
Id: 24
Id: 25
Id: 26
Id: 27
Id: 28
Id: 29
Id: 30
Id: 31
Id: 32
Id: 33
Id: 34
Id: 35
Id: 36
Id: 37
Id: 38
Id: 39
Id: 40
Id: 41
Id: 42
Id: 43
Id: 44
Id: 45
Id: 46
Id: 47
Id: 48
Id: 49
Id: 50
Id: 51
Id: 52
Id: 53
Id: 54
Id: 55
Id: 56
Id: 57
Id: 58
Id: 59
Id: 60
Id: 61
Id: 62
Id: 63
Id: 64
Id: 65
Id: 66
Id: 67
Id: 68
Id: 69
Id: 70
Id: 71
Id: 72
Id: 73
Id: 74
Id: 75
Id: 76
Id: 77
Id: 78
Id: 79
Id: 80
Id: 81
Id: 82
Id: 83
Id: 84
Id: 85
Id: 86
Id: 87
Id: 88
Id: 89
Id: 90
Id: 91
Id: 92
Id: 93
Id: 94
Id: 95
Id: 96
Id: 97
Id: 98
Id: 99
Id: 100
Id: 101
Id: 102
Id: 103
Id: 104
Id: 105
Id: 106
Id: 107
Id: 108
Id: 109
Id: 110
Id: 111
Id: 112
Id: 113
Id: 114
Id: 115
Id: 116
Id: 117
Id: 118
Id: 119
Id: 120
Id: 121
Id: 122
Id: 123
Id: 124
Id: 125
Id: 126
Id: 127
Id: 128
Id: 129
Id: 130
Id: 131
Id: 132
Id: 133
Id: 134
Id: 135
Id: 136
Id: 137
Id: 138
Id: 139
Id: 140
Id: 141
Id: 142
Id: 143
Id: 144
Id: 145
Id: 146
Id: 147
Id: 148
Id: 149
Id: 150
Id: 151
Id: 152
Id: 153
Id: 154
Id: 155
Id: 156
Id: 157
Id: 158
Id: 159
Id: 160
Id: 161
Id: 162
Id: 163
Id: 164
Id: 165
Id: 166
Id: 167
Id: 168
Id: 169
Id: 170
Id: 171
Id: 172
Id: 173
Id: 174
Id: 175
Id: 176
Id: 177
Id: 178
Id: 179
Id: 180
Id: 181
Id: 182
Id: 183
Id: 184
Id: 185
Id: 186
Id: 187
Id: 188
Id: 189
Id: 190
Id: 191
Id: 192
Id: 193
Id: 194
Id: 195
Id: 196
Id: 197
Id: 198
Id: 199
Id: 200
Id: 201
Id: 202
Id: 203
Id: 204
Id: 205
Id: 206
Id: 207
Id: 208
Id: 209
Id: 210
Id: 211
Id: 212
Id: 213
Id: 214
Id: 215
Id: 216
Id: 217
Id: 218
Id: 219
Id: 220
Id: 221
Id: 222
Id: 223
Id: 224
Id: 225
Id: 226
Id: 227
Id: 228
Id: 229
Id: 230
Id: 231
Id: 232
Id: 233
Id: 234
Id: 235
Id: 236
Id: 237
Id: 238
Id: 239
Id: 240
Id: 241
Id: 242
Id: 243
Id: 244
Id: 245
Id: 246
Id: 247
Id: 248
Id: 249
Id: 250
Id: 251
Id: 252
Id: 253
Id: 254
Id: 255
Id: 256
Id: 257
Id: 258
Id: 259
Id: 260
Id: 261
Id: 262
Id: 263
Id: 264
Id: 265
Id: 266
Id: 267
Id: 268
Id: 269
Id: 270
Id: 271
Id: 272
Id: 273
Id: 274
Id: 275
Id: 276
Id: 277
Id: 278
Id: 279
Id: 280
Id: 281
Id: 282
Id: 283
Id: 284
Id: 285
Id: 286
Id: 287
Id: 288
Id: 289
Id: 290
Id: 291
Id: 292
Id: 293
Id: 294
Id: 295
Id: 296
Id: 297
Id: 298
Id: 299
Id: 300
Id: 301
Id: 302
Id: 303
Id: 304
Id: 305
Id: 306
Id: 307
Id: 308
Id: 309
Id: 310
Id: 311
Id: 312
Id: 313
Id: 314
Id: 315
Id: 316
Id: 317
Id: 318
Id: 319
Id: 320
Id: 321
Id: 322
Id: 323
Id: 324
Id: 325
Id: 326
Id: 327
Id: 328
Id: 329
Id: 330
Id: 331
Id: 332
Id: 333
Id: 334
Id: 335
Id: 336
Id: 337
Id: 338
Id: 339
Id: 340
Id: 341
Id: 342
Id: 343
Id: 344
Id: 345
Id: 346
Id: 347
Id: 348
Id: 349
Id: 350
Id: 351
Id: 352
Id: 353
Id: 354
Id: 355
Id: 356
Id: 357
Id: 358
Id: 359
Id: 360
Id: 361
Id: 362
Id: 363
Id: 364
Id: 365
Id: 366
Id: 367
Id: 368
Id: 369
Id: 370
Id: 371
Id: 372
Id: 373
Id: 374
Id: 375
Id: 376
Id: 377
Id: 378
Id: 379
Id: 380
Id: 381
Id: 382
Id: 383
Id: 384
Id: 385
Id: 386
Id: 387
Id: 388
Id: 389
Id: 390
Id: 391
Id: 392
Id: 393
Id: 394
Id: 395
Id: 396
Id: 397
Id: 398
Id: 399
Id: 400
Id: 401
Id: 402
Id: 403
Id: 404
Id: 405
Id: 406
Id: 407
Id: 408
Id: 409
Id: 410
Id: 411
Id: 412
Id: 413
Id: 414
Id: 415
Id: 416
Id: 417
Id: 418
Id: 419
Id: 420
Id: 421
Id: 422
Id: 423
Id: 424
Id: 425
Id: 426
Id: 427
Id: 428
Id: 429
Id: 430
Id: 431
Id: 432
Id: 433
Id: 434
Id: 435
Id: 436
Id: 437
Id: 438
Id: 439
Id: 440
Id: 441
Id: 442
Id: 443
Id: 444
Id: 445
Id: 446
Id: 447
Id: 448
Id: 449
Id: 450
Id: 451
Id: 452
Id: 453
Id: 454
Id: 455
Id: 456
Id: 457
Id: 458
Id: 459
Id: 460
Id: 461
Id: 462
Id: 463
Id: 464
Id: 465
Id: 466
Id: 467
Id: 468
Id: 469
Id: 470
Id: 471
Id: 472
Id: 473
Id: 474
Id: 475
Id: 476
Id: 477
Id: 478
Id: 479
Id: 480
Id: 481
Id: 482
Id: 483
Id: 484
Id: 485
Id: 486
Id: 487
Id: 488
Id: 489
Id: 490
Id: 491
Id: 492
Id: 493
Id: 494
Id: 495
Id: 496
Id: 497
Id: 498
Id: 499
Id: 500
Id: 501
Id: 502
Id: 503
Id: 504
Id: 505
Id: 506
Id: 507
Id: 508
Id: 509
Id: 510
Id: 511
Id: 512
Id: 513
Id: 514
Id: 515
Id: 516
Id: 517
Id: 518
Id: 519
Id: 520
Id: 521
Id: 522
Id: 523
Id: 524
Id: 525
Id: 526
Id: 527
Id: 528
Id: 529
Id: 530
Id: 531
Id: 532
Id: 533
Id: 534
Id: 535
Id: 536
Id: 537
Id: 538
Id: 539
Id: 540
Id: 541
Id: 542
Id: 543
Id: 544
Id: 545
Id: 546
Id: 547
Id: 548
Id: 549
Id: 550
Id: 551
Id: 552
Id: 553
Id: 554
Id: 555
Id: 556
Id: 557
Id: 558
Id: 559
Id: 560
Id: 561
Id: 562
Id: 563
Id: 564
Id: 565
Id: 566
Id: 567
Id: 568
Id: 569
Id: 570
Id: 571
Id: 572
Id: 573
Id: 574
Id: 575
Id: 576
Id: 577
Id: 578
Id: 579
Id: 580
Id: 581
Id: 582
Id: 583
Id: 584
Id: 585
Id: 586
Id: 587
Id: 588
Id: 589
Id: 590
Id: 591
Id: 592
Id: 593
Id: 594
Id: 595
Id: 596
Id: 597
Id: 598
Id: 599
Id: 600
Id: 601
Id: 602
Id: 603
Id: 604
Id: 605
Id: 606
Id: 607
Id: 608
Id: 609
Id: 610
Id: 611
Id: 612
Id: 613
Id: 614
Id: 615
Id: 616
Id: 617
Id: 618
Id: 619
Id: 620
Id: 621
Id: 622
Id: 623
Id: 624
Id: 625
Id: 626
Id: 627
Id: 628
Id: 629
Id: 630
Id: 631
Id: 632
Id: 633
Id: 634
Id: 635
Id: 636
Id: 637
Id: 638
Id: 639
Id: 640
Id: 641
Id: 642
Id: 643
Id: 644
Id: 645
Id: 646
Id: 647
Id: 648
Id: 649
Id: 650
Id: 651
Id: 652
Id: 653
Id: 654
Id: 655
Id: 656
Id: 657
Id: 658
Id: 659
Id: 660
Id: 661
Id: 662
Id: 663
Id: 664
Id: 665
Id: 666
Id: 667
Id: 668
Id: 669
Id: 670
Id: 671
Id: 672
Id: 673
Id: 674
Id: 675
Id: 676
Id: 677
Id: 678
Id: 679
Id: 680
Id: 681
Id: 682
Id: 683
Id: 684
Id: 685
Id: 686
Id: 687
Id: 688
Id: 689
Id: 690
Id: 691
Id: 692
Id: 693
Id: 694
Id: 695
Id: 696
Id: 697
Id: 698
Id: 699
Id: 700
Id: 701
Id: 702
Id: 703
Id: 704
Id: 705
Id: 706
Id: 707
Id: 708
Id: 709
Id: 710
Id: 711
Id: 712
Id: 713
Id: 714
Id: 715
Id: 716
Id: 717
Id: 718
Id: 719
Id: 720
Id: 721
Id: 722
Id: 723
Id: 724
Id: 725
Id: 726
Id: 727
Id: 728
Id: 729
Id: 730
Id: 731
Id: 732
Id: 733
Id: 734
Id: 735
Id: 736
Id: 737
Id: 738
Id: 739
Id: 740
Id: 741
Id: 742
Id: 743
Id: 744
Id: 745
Id: 746
Id: 747
Id: 748
Id: 749
Id: 750
Id: 751
Id: 752
Id: 753
Id: 754
Id: 755
Id: 756
Id: 757
Id: 758
Id: 759
Id: 760
Id: 761
Id: 762
Id: 763
Id: 764
Id: 765
Id: 766
Id: 767
Id: 768
Id: 769
Id: 770
Id: 771
Id: 772
Id: 773
Id: 774
Id: 775
Id: 776
Id: 777
Id: 778
Id: 779
Id: 780
Id: 781
Id: 782
Id: 783
Id: 784
Id: 785
Id: 786
Id: 787
Id: 788
Id: 789
Id: 790
Id: 791
Id: 792
Id: 793
Id: 794
Id: 795
Id: 796
Id: 797
Id: 798
Id: 799
Id: 800
Id: 801
Id: 802
Id: 803
Id: 804
Id: 805
Id: 806
Id: 807
Id: 808
Id: 809
Id: 810
Id: 811
Id: 812
Id: 813
Id: 814
Id: 815
Id: 816
Id: 817
Id: 818
Id: 819
Id: 820
Id: 821
Id: 822
Id: 823
Id: 824
Id: 825
Id: 826
Id: 827
Id: 828
Id: 829
Id: 830
Id: 831
Id: 832
Id: 833
Id: 834
Id: 835
Id: 836
Id: 837
Id: 838
Id: 839
Id: 840
Id: 841
Id: 842
Id: 843
Id: 844
Id: 845
Id: 846
Id: 847
Id: 848
Id: 849
Id: 850
Id: 851
Id: 852
Id: 853
Id: 854
Id: 855
Id: 856
Id: 857
Id: 858
Id: 859
Id: 860
Id: 861
Id: 862
Id: 863
Id: 864
Id: 865
Id: 866
Id: 867
Id: 868
Id: 869
Id: 870
Id: 871
Id: 872
Id: 873
Id: 874
Id: 875
Id: 876
Id: 877
Id: 878
Id: 879
Id: 880
Id: 881
Id: 882
Id: 883
Id: 884
Id: 885
Id: 886
Id: 887
Id: 888
Id: 889
Id: 890
Id: 891
Id: 892
Id: 893
Id: 894
Id: 895
Id: 896
Id: 897
Id: 898
Id: 899
Id: 900
Id: 901
Id: 902
Id: 903
Id: 904
Id: 905
Id: 906
Id: 907
Id: 908
Id: 909
Id: 910
Id: 911
Id: 912
Id: 913
Id: 914
Id: 915
Id: 916
Id: 917
Id: 918
Id: 919
Id: 920
Id: 921
Id: 922
Id: 923
Id: 924
Id: 925
Id: 926
Id: 927
Id: 928
Id: 929
Id: 930
Id: 931
Id: 932
Id: 933
Id: 934
Id: 935
Id: 936
Id: 937
Id: 938
Id: 939
Id: 940
Id: 941
Id: 942
Id: 943
Id: 944
Id: 945
Id: 946
Id: 947
Id: 948
Id: 949
Id: 950
Id: 951
Id: 952
Id: 953
Id: 954
Id: 955
Id: 956
Id: 957
Id: 958
Id: 959
Id: 960
Id: 961
Id: 962
Id: 963
Id: 964
Id: 965
Id: 966
Id: 967
Id: 968
Id: 969
Id: 970
Id: 971
Id: 972
Id: 973
Id: 974
Id: 975
Id: 976
Id: 977
Id: 978
Id: 979
Id: 980
Id: 981
Id: 982
Id: 983
Id: 984
Id: 985
Id: 986
Id: 987
Id: 988
Id: 989
Id: 990
Id: 991
Id: 992
Id: 993
Id: 994
Id: 995
Id: 996
Id: 997
Id: 998
Id: 999
Id: 1000
Id: 1001
Id: 1002
Id: 1003
Id: 1004
Id: 1005
Id: 1006
Id: 1007
Id: 1008
Id: 1009
Id: 1010
Id: 1011
Id: 1012
Id: 1013
Id: 1014
Id: 1015
Id: 1016
Id: 1017
Id: 1018
Id: 1019
Id: 1020
Id: 1021
Id: 1022
Id: 1023
Id: 1024
Id: 1025
Id: 1026
Id: 1027
Id: 1028
Id: 1029
Id: 1030
Id: 1031
Id: 1032
Id: 1033
Id: 1034
Id: 1035
Id: 1036
Id: 1037
Id: 1038
Id: 1039
Id: 1040
Id: 1041
Id: 1042
Id: 1043
Id: 1044
Id: 1045
Id: 1046
Id: 1047
Id: 1048
Id: 1049
Id: 1050
Id: 1051
Id: 1052
Id: 1053
Id: 1054
Id: 1055
Id: 1056
Id: 1057
Id: 1058
Id: 1059
Id: 1060
Id: 1061
Id: 1062
Id: 1063
Id: 1064
Id: 1065
Id: 1066
Id: 1067
Id: 1068
Id: 1069
Id: 1070
Id: 1071
Id: 1072
Id: 1073
Id: 1074
Id: 1075
Id: 1076
Id: 1077
Id: 1078
Id: 1079
Id: 1080
Id: 1081
Id: 1082
Id: 1083
Id: 1084
Id: 1085
Id: 1086
Id: 1087
Id: 1088
Id: 1089
Id: 1090
Id: 1091
Id: 1092
Id: 1093
Id: 1094
Id: 1095
Id: 1096
Id: 1097
Id: 1098
Id: 1099
Id: 1100
Id: 1101
Id: 1102
Id: 1103
Id: 1104
Id: 1105
Id: 1106
Id: 1107
Id: 1108
Id: 1109
Id: 1110
Id: 1111
Id: 1112
Id: 1113
Id: 1114
Id: 1115
Id: 1116
Id: 1117
Id: 1118
Id: 1119
Id: 1120
Id: 1121
Id: 1122
Id: 1123
Id: 1124
Id: 1125
Id: 1126
Id: 1127
Id: 1128
Id: 1129
Id: 1130
Id: 1131
Id: 1132
Id: 1133
Id: 1134
Id: 1135
Id: 1136
Id: 1137
Id: 1138
Id: 1139
Id: 1140
Id: 1141
Id: 1142
Id: 1143
Id: 1144
Id: 1145
Id: 1146
Id: 1147
Id: 1148
Id: 1149
Id: 1150
Id: 1151
Id: 1152
Id: 1153
Id: 1154
Id: 1155
Id: 1156
Id: 1157
Id: 1158
Id: 1159
Id: 1160
Id: 1161
Id: 1162
Id: 1163
Id: 1164
Id: 1165
Id: 1166
Id: 1167
Id: 1168
Id: 1169
Id: 1170
Id: 1171
Id: 1172
Id: 1173
Id: 1174
Id: 1175
Id: 1176
Id: 1177
Id: 1178
Id: 1179
Id: 1180
Id: 1181
Id: 1182
Id: 1183
Id: 1184
Id: 1185
Id: 1186
Id: 1187
Id: 1188
Id: 1189
Id: 1190
Id: 1191
Id: 1192
Id: 1193
Id: 1194
Id: 1195
Id: 1196
Id: 1197
Id: 1198
Id: 1199
Id: 1200
Id: 1201
Id: 1202
Id: 1203
Id: 1204
Id: 1205
Id: 1206
Id: 1207
Id: 1208
Id: 1209
Id: 1210
Id: 1211
Id: 1212
Id: 1213
Id: 1214
Id: 1215
Id: 1216
Id: 1217
Id: 1218
Id: 1219
Id: 1220
Id: 1221
Id: 1222
Id: 1223
Id: 1224
Id: 1225
Id: 1226
Id: 1227
Id: 1228
Id: 1229
Id: 1230
Id: 1231
Id: 1232
Id: 1233
Id: 1234
Id: 1235
Id: 1236
Id: 1237
Id: 1238
Id: 1239
Id: 1240
Id: 1241
Id: 1242
Id: 1243
Id: 1244
Id: 1245
Id: 1246
Id: 1247
Id: 1248
Id: 1249
Id: 1250
Id: 1251
Id: 1252
Id: 1253
Id: 1254
Id: 1255
Id: 1256
Id: 1257
Id: 1258
Id: 1259
Id: 1260
Id: 1261
Id: 1262
Id: 1263
Id: 1264
Id: 1265
Id: 1266
Id: 1267
Id: 1268
Id: 1269
Id: 1270
Id: 1271
Id: 1272
Id: 1273
Id: 1274
Id: 1275
Id: 1276
Id: 1277
Id: 1278
Id: 1279
Id: 1280
Id: 1281
Id: 1282
Id: 1283
Id: 1284
Id: 1285
Id: 1286
Id: 1287
Id: 1288
Id: 1289
Id: 1290
Id: 1291
Id: 1292
Id: 1293
Id: 1294
Id: 1295
Id: 1296
Id: 1297
Id: 1298
Id: 1299
Id: 1300
Id: 1301
Id: 1302
Id: 1303
Id: 1304
Id: 1305
Id: 1306
Id: 1307
Id: 1308
Id: 1309
Id: 1310
Id: 1311
Id: 1312
Id: 1313
Id: 1314
Id: 1315
Id: 1316
Id: 1317
Id: 1318
Id: 1319
Id: 1320
Id: 1321
Id: 1322
Id: 1323
Id: 1324
Id: 1325
Id: 1326
Id: 1327
Id: 1328
Id: 1329
Id: 1330
Id: 1331
Id: 1332
Id: 1333
Id: 1334
Id: 1335
Id: 1336
Id: 1337
Id: 1338
Id: 1339
Id: 1340
Id: 1341
Id: 1342
Id: 1343
Id: 1344
Id: 1345
Id: 1346
Id: 1347
Id: 1348
Id: 1349
Id: 1350
Id: 1351
Id: 1352
Id: 1353
Id: 1354
Id: 1355
Id: 1356
Id: 1357
Id: 1358
Id: 1359
Id: 1360
Id: 1361
Id: 1362
Id: 1363
Id: 1364
Id: 1365
Id: 1366
Id: 1367
Id: 1368
Id: 1369
Id: 1370
Id: 1371
Id: 1372
Id: 1373
Id: 1374
Id: 1375
Id: 1376
Id: 1377
Id: 1378
Id: 1379
Id: 1380
Id: 1381
Id: 1382
Id: 1383
Id: 1384
Id: 1385
Id: 1386
Id: 1387
Id: 1388
Id: 1389
Id: 1390
Id: 1391
Id: 1392
Id: 1393
Id: 1394
Id: 1395
Id: 1396
Id: 1397
Id: 1398
Id: 1399
Id: 1400
Id: 1401
Id: 1402
Id: 1403
Id: 1404
Id: 1405
Id: 1406
Id: 1407
Id: 1408
Id: 1409
Id: 1410
Id: 1411
Id: 1412
Id: 1413
Id: 1414
Id: 1415
Id: 1416
Id: 1417
Id: 1418
Id: 1419
Id: 1420
Id: 1421
Id: 1422
Id: 1423
Id: 1424
Id: 1425
Id: 1426
Id: 1427
Id: 1428
Id: 1429
Id: 1430
Id: 1431
Id: 1432
Id: 1433
Id: 1434
Id: 1435
Id: 1436
Id: 1437
Id: 1438
Id: 1439
Id: 1440
Id: 1441
Id: 1442
Id: 1443
Id: 1444
Id: 1445
Id: 1446
Id: 1447
Id: 1448
Id: 1449
Id: 1450
Id: 1451
Id: 1452
Id: 1453
Id: 1454
Id: 1455
Id: 1456
Id: 1457
Id: 1458